feat: add density:gm-per-centim3
cognitedata/units-catalog pull request #123
Opened 2024-12-04 10:33 UTC by Marwen94

2024-12-04 10:53 UTC, AL1099966 approved these changes

2025-01-06 10:00 UTC, evertoncolling commented on versions/v1/units.json
> +    ],
You have duplicated aliases in the list. Please remove them as suggested below:

```suggestion
    "aliasNames": [
      "Gram per Cubic Centimeter",
      "gram per CM3",
      "G PER CM3",
      "g per CM3",
      "g / Cubic Centimeter",
      "Gram / Cubic Centimeter",
      "Gram / cubic centimeter",
      "g / cm³",
      "gram / cubic centimeter",
      "Gram per cubic centimeter",
      "Gram per CM3",
      "gram per cubic centimeter",
      "GM per cm³",
      "GM / Cubic centimeter",
      "g / CM3",
      "g per cubic centimeter",
      "GM per cubic centimeter",
      "gram / Cubic centimeter",
      "GM / cubic centimeter",
      "GM / CM3",
      "GM per CM3",
      "g per Cubic Centimeter",
      "GM / cm³",
      "Gram Per Cubic Centimeter",
      "g / cubic centimeter",
      "Gram per cm³",
      "gram per cm³",
      "gram / cm³",
      "g per cm³",
      "gram / CM3",
      "gram per Cubic Centimeter",
      "GM PER CM3",
      "GM per Cubic Centimeter",
      "Gram / CM3",
      "Gram / cm³"
    ],
```

2025-01-06 10:00 UTC, evertoncolling requested changes
Update the list of aliases with only unique entries.

2025-01-06 17:08 UTC, Marwen94 commented
> Update the list of aliases with only unique entries.

Done

2025-01-06 17:17 UTC, evertoncolling approved these changes
Looks good to me!

2025-01-06 17:18 UTC, merged

2025-01-06 17:19 UTC, evertoncolling commented
We'll release a new version of the catalog library tomorrow, but be mindful it can take a couple of weeks for the update to be deployed to all CDF clusters.