feat: new units
cognitedata/units-catalog pull request #32
Opened 2023-11-28 04:35 UTC by jpriou

- poise
- centipoise
- ppb

2023-11-28 08:01 UTC, jpriou commented
I am struggling a bit to add a few units, since they don't appear in qudt.org.
- [Volume](https://qudt.org/vocab/quantitykind/Volume): MMcf (i.e. 1e+6 ft3)
- [VolumeFlowRate](https://qudt.org/vocab/quantitykind/VolumeFlowRate): MMcfd (i.e. 1e+6 ft3/day)

These units are quite common in oil & gas. Any advice on adding the units?

2023-12-08 04:06 UTC, jpriou commented on versions/v1/unitSystems.json
> +        "unitExternalId": "electric_power:v-a"
Created a new entry here.
I hesitated putting it under the existing `Power` quantity (`W`). I created a new entry because this unit is specifically related to `Electric Power`.
See note on qudt (https://qudt.org/vocab/unit/W)

![image](https://github.com/cognitedata/units-catalog/assets/62795297/380a0d30-d033-48f2-93f9-b179588f4d11)

2023-12-11 13:02 UTC, evertoncolling commented on versions/v1/unitSystems.json
> +        "unitExternalId": "electric_power:v-a"
Today we don't support "derived quantities", like `Power` -> `Electric Power`. In order to keep the catalog as simple as possible, the current philosophy is to group all "convertible" units under a single quantity.

For this PR to be approved we recommend removing "Electric Power" and adding any extra unit needed directly under "Power".

2023-12-11 13:05 UTC, evertoncolling commented on versions/v1/units.json
> +  },
We should not fake qudt.org references. I recommend removing this unit from this PR and we take it on a new one.

There are a couple of changes that could be accepted here:
- Make a PR to qudt.org adding this unit (it's a clear candidate, since the base units are there already)
- Look for a reference on other unit catalogs for this particular unit
- Leave source blank and treat is as a custom unit (only if options above are not successful)

2023-12-11 17:22 UTC, jpriou commented on versions/v1/unitSystems.json
> +        "unitExternalId": "electric_power:v-a"
addressed by [/6c687a5](https://github.com/cognitedata/units-catalog/pull/32/commits/6c687a59d789cca78012c72a88a2d24c3b80524f)

2023-12-11 17:22 UTC, jpriou commented on versions/v1/units.json
> +  },
Removed. Will make another PR for this.

2023-12-12 20:12 UTC, evertoncolling commented on versions/v1/units.json
> +    "symbol": "KVA",
```suggestion
    "symbol": "kV⋅A",
```

2023-12-12 20:13 UTC, evertoncolling commented on versions/v1/units.json
> +      "KVA"
```suggestion
      "KVA",
      "kVA",
      "kV⋅A"
```

2023-12-12 20:16 UTC, evertoncolling commented on versions/v1/units.json
> +    "symbol": "MVA",
```suggestion
    "symbol": "MV⋅A",
```

2023-12-12 20:17 UTC, evertoncolling commented on versions/v1/units.json
> +      "MVA"
```suggestion
      "MVA",
      "MV⋅A"
```

2023-12-12 20:18 UTC, evertoncolling commented on versions/v1/units.json
> +    "symbol": "VA",
```suggestion
    "symbol": "V⋅A",
```

2023-12-12 20:18 UTC, evertoncolling commented on versions/v1/units.json
> +      "VA"
```suggestion
      "VA",
      "V⋅A"
```

2023-12-12 20:18 UTC, evertoncolling commented on versions/v1/units.json
> +      "multiplier": 1000,
```suggestion
      "multiplier": 1000.0,
```

2023-12-12 20:19 UTC, evertoncolling commented on versions/v1/units.json
> +      "multiplier": 1e06,
```suggestion
      "multiplier": 1.0e06,
```

2023-12-12 20:19 UTC, evertoncolling commented on versions/v1/units.json
> +      "multiplier": 1,
```suggestion
      "multiplier": 1.0,
```

2023-12-12 20:21 UTC, evertoncolling commented
@jpriou I found some small points for improvements/corrections. @hgocog could you have a check too? Just to confirm I haven't missed anything.

2023-12-13 04:34 UTC, jpriou commented
Thanks for the notes. I have modified the PR, as requested.

2023-12-13 14:41 UTC, hgocog commented on versions/v1/units.json
> +    "longName": "gram per cubic meter",
"longName":"Gram Per Cubic Meter",

2023-12-13 14:42 UTC, hgocog commented on versions/v1/units.json
> +    "symbol": "g/m³",
"aliasNames":[
            "Gram per Cubic Meter",
            "gram per M3",
            "g per M3",
            "g / Cubic Meter",
            "Gram / Cubic Meter",
            "Gram / cubic meter",
            "g / m³",
            "gram / cubic meter",
            "Gram per cubic meter",
            "Gram per M3",
            "gram per cubic metre",
            "GM per m³",
            "gram per cubic meter",
            "GM / Cubic Meter",
            "g / M3",
            "g per cubic meter",
            "GM per cubic meter",
            "gram / Cubic Meter",
            "GM / cubic meter",
            "GM / M3",
            "GM per M3",
            "g per Cubic Meter",
            "GM per cubic metre",
            "GM / m³",
            "Gram Per Cubic Meter",
            "GM / cubic metre",
            "g / cubic metre",
            "Gram per m³",
            "gram per m³",
            "gram / m³",
            "Gram / cubic metre",
            "g per m³",
            "g / cubic meter",
            "gram / M3",
            "g per cubic metre",
            "gram / cubic metre",
            "gram per Cubic Meter",
            "GM PER M3",
            "GM per Cubic Meter",
            "Gram Per Cubic Metre",
            "Gram / M3",
            "Gram per cubic metre",
            "Gram / m³"
        ],

2023-12-13 14:45 UTC, hgocog commented on versions/v1/units.json
> +    ],
"aliasNames":[
            "cP",
            "centipoise",
            "CentiPOISE",
            "Centipoise"
        ],

2023-12-13 14:46 UTC, hgocog commented on versions/v1/units.json
> +    ],
"aliasNames":[
            "P",
            "Poise",
            "POISE",
            "poise"
        ],

2023-12-13 14:47 UTC, hgocog commented on versions/v1/units.json
> +    ],
"aliasNames":[
            "KiloV A",
            "KiloV ampere",
            "Kilovolt A",
            "kV ampere",
            "kilovolt A",
            "kilovolt ampere",
            "kV ⋅ A",
            "Kilovolt Ampere",
            "Kilovolt ampere",
            "kV A"
        ],

2023-12-13 14:47 UTC, hgocog commented on versions/v1/units.json
> +    "symbol": "kV.A",
"symbol":"kV⋅A",

2023-12-13 14:49 UTC, hgocog commented on versions/v1/units.json
> +    ],
"aliasNames":[
            "V ⋅ A",
            "volt A",
            "V ampere",
            "volt ampere",
            "V A"
        ],

2023-12-13 14:50 UTC, hgocog commented on versions/v1/units.json
> +    "symbol": "V.A",
"symbol":"V⋅A",

2023-12-13 14:50 UTC, hgocog commented on versions/v1/units.json
> +    ],
"aliasNames":[
            "Cubic Foot per DAY",
            "Cubic Foot / DAY",
            "ft³ / day",
            "Cubic Foot per Day",
            "Cubic Foot / Day",
            "FT3 per DAY",
            "cubic foot per day",
            "FT3 PER DAY",
            "ft³ per day",
            "cubic foot / Day",
            "FT3 / DAY",
            "ft³ per Day",
            "Cubic Foot Per Day",
            "Cubic Foot per day",
            "FT3 / Day",
            "cubic foot / day",
            "cubic foot per Day",
            "ft³ / Day",
            "FT3 / day",
            "ft³ / DAY",
            "FT3 per day",
            "cubic foot per DAY",
            "FT3 per Day",
            "Cubic Foot / day",
            "cubic foot / DAY",
            "ft³ per DAY"
        ],

2023-12-13 14:58 UTC, hgocog requested changes
Hi  @jpriou, 
that is really great! Thank you for adding the units!! 
I only have minor reviews on consistency. In my view:

My comments on `symbol` fields  are mandatory:
-  please use `⋅` in symbol for multiplication (as in qudt)
- for example please use `MV⋅A` instead of `MV.A`

Changes of `aliasNames` fields are optional I just copied the suggestions.

2023-12-13 17:39 UTC, jpriou commented
Included all the comments. ✅

2023-12-13 18:02 UTC, hgocog approved these changes

2023-12-13 18:06 UTC, merged