feat: new units
cognitedata/units-catalog pull request #35
Opened 2024-01-18 07:15 UTC by jpriou

- frequency:per-min
- pressure:kilogm_f-per-centim2
- linear_density:kilogm-per-m (added new entry to `unitSystems.json`)
- volume_flow_rate:l-per-hr
- velocity:millim-per-sec
- volume:mega-m3
- pressure:millim-h2o
- time:mo
- volume_flow_rate:kilo-ft3-per-day
- inverse_length:per-m (added new entry to `unitSystems.json`)

2024-01-22 12:42 UTC, matiascognite requested changes
Check the conversion factors

2024-01-22 12:53 UTC, matiascognite commented on versions/v1/units.json
> +      "/ min"
Nit: In other units, we have " /..." (space between " and /)
I like this better, without the space

2024-01-22 15:30 UTC, jpriou commented on versions/v1/units.json
> +      "multiplier": 60.0,
Yes--you are right. It should be 1/60.
In to https://qudt.org/vocab/unit/PER-MIN, they had 0.01666666666666666666666666666666667.
Will update.

2024-01-22 16:00 UTC, jpriou commented on versions/v1/units.json
> +      "multiplier": 2.551442976e06,
Thanks for checking this. I actually didn't mean to have lunar months. I am after the calendar months. 
I think what you suggest is good.
So, 365.25/12 days = 2.6298e+6 s (instead of ~~2.551442976e06~~)

2024-01-23 09:37 UTC, jpriou commented on versions/v1/units.json
> +      "multiplier": 2.551442976e06,
Updated by [d6694c5](https://github.com/cognitedata/units-catalog/pull/35/commits/d6694c53048299c375c38c5c3962c2d8f9e47063)

2024-01-23 09:41 UTC, jpriou commented on versions/v1/units.json
> +      "multiplier": 60.0,
Updated by [3a37660](https://github.com/cognitedata/units-catalog/pull/35/commits/3a376604e3d7a5f3f2c968be091aec98798ba6d7)

2024-01-23 12:42 UTC, matiascognite commented on versions/v1/units.json
> +      "multiplier": 9.80665,
nitpick: this number is based on the weight of water of 1kg/liter, which is 
0.003% too high at 4 degrees (maximum density). However, I see other sources use this multiplier, so It should be fine

2024-01-23 12:43 UTC, matiascognite approved these changes
The units look good to me, from a mathematical point of view. Nice if you also get a review from an engineering point of view.

2024-01-23 13:32 UTC, evertoncolling commented on versions/v1/units.json
> +      "multiplier": 2.551442976e06,
I agree with the discussion here. I found this reference on qudt: [https://qudt.org/vocab/unit/MO](https://qudt.org/vocab/unit/MO), but it seems to be a lunar month definition.

We could use this one from UNECE, where 1 month equals to `2,629 800 x 10⁶ s` (just like you calculated, but from a real traceable reference).

2024-01-23 13:36 UTC, evertoncolling commented on versions/v1/units.json
> +      "multiplier": 2.551442976e06,
I suggest updating the reference to UNECE unit catalog, which you can find [here](https://unece.org/trade/uncefact/cl-recommendations#:~:text=Rec%2020%20%E2%80%93%20Codes%20for%20Units,quantities%20used%20in%20international%20trade.)

2024-01-23 13:39 UTC, evertoncolling commented on versions/v1/units.json
> +      "/ min"
I agree that we need some consistency on aliases. I'm having a discussion with @hgocog on what pattern should we stick to to avoid having multiple variations and enforcing consistency.

2024-01-23 13:39 UTC, evertoncolling commented on versions/v1/units.json
> +      "/ min"
Not a blocker for this PR though 🙂

2024-01-23 13:49 UTC, evertoncolling commented on versions/v1/units.json
> +      "multiplier": 9.80665,
Yes, this is based on a convention of a state. Tricky subject, as it depends on the water temperature, but I cross checked and this is the common conversion factor.

2024-01-23 13:54 UTC, evertoncolling commented on versions/v1/units.json
> +    "source": "Custom based on qudt.org - https://qudt.org/vocab/unit/M3",
This unit is available on Energistics, which you can check [here](https://www.energistics.org/energistics-unit-of-measure-standard). We can then update the source to it.

2024-01-24 07:06 UTC, jpriou commented on versions/v1/units.json
> +      "multiplier": 2.551442976e06,
Thanks!
Updated the source to "UNECE: Codes for Units of Measure Used in International Trade (latest revision) - https://unece.org/trade/uncefact/cl-recommendations"

2024-01-24 19:39 UTC, evertoncolling commented on versions/v1/units.json
> +    "source": "UNECE: Codes for Units of Measure Used in International Trade (latest revision) - https://unece.org/trade/uncefact/cl-recommendations",
```suggestion
    "source": "UNECE: Codes for Units of Measure Used in International Trade (revision 2021) - https://unece.org/trade/uncefact/cl-recommendations",
```
The current latest revision is from 2021, but they could add a new revision some time in the future, so it's better to pinpoint which one we took as reference.

2024-01-24 19:40 UTC, evertoncolling commented on versions/v1/units.json
> +    "source": "Energistics: Unit of Measure Standard - https://www.energistics.org/energistics-unit-of-measure-standard",
```suggestion
    "source": "Energistics: Unit of Measure Standard (revision June 2014) - https://www.energistics.org/energistics-unit-of-measure-standard",
```
Here as well, let's mention which revision we used as a source

2024-01-25 08:40 UTC, jpriou commented on versions/v1/units.json
> +    "sourceReference": "https://rds.posccaesar.org/ontology/plm/rdl/PCA_100005357"
@evertoncolling, I just realized that I forgot to add this unit too.
I used the same ref. as what you had for the other gauge pressures.
According to `"Experimental Methods and Instrumentation for Chemical Engineers - ISBN 9780444538055 - https://isbnsearch.org/isbn/9780444538055"`, 

```
[...] the National Institute of Standards and Technology have retained 101.325 kPa as their reference condition. 
```
So the same conversion should apply. Let me know if anything else is needed.

2024-01-25 11:59 UTC, evertoncolling commented on versions/v1/units.json
> +    "sourceReference": "https://rds.posccaesar.org/ontology/plm/rdl/PCA_100005357"
Looks good to me!

2024-01-25 12:02 UTC, evertoncolling approved these changes
Looks good to me! We just need to bump up the version before merging it.

2024-01-25 19:50 UTC, merged