add attenuation unit
cognitedata/units-catalog pull request #88
Opened 2024-07-08 17:17 UTC by spalla2-slb

1. Add `dB` and `bel` units for Attenuation quantity
2. Registered `dB` under all three unit systems (Default, SI and Imperial).

2024-07-11 09:31 UTC, evertoncolling commented on versions/v1/units.json
> +    "name": "dB",
```suggestion
    "name": "DeciB",
```

2024-07-11 09:31 UTC, evertoncolling commented on versions/v1/units.json
> +    "externalId": "attenuation:db",
```suggestion
    "externalId": "attenuation:decib",
```

2024-07-11 09:32 UTC, evertoncolling commented on versions/v1/units.json
> +    "longName": "Decibels",
```suggestion
    "longName": "Decibel",
```

2024-07-11 09:34 UTC, evertoncolling commented on versions/v1/units.json
> +    "aliasNames": [],
We should add at a few entries to alias names, it should contain at least the `symbol` and the `longName`. Later, users can contribute with more known aliases.

2024-07-11 09:35 UTC, evertoncolling commented on versions/v1/units.json
> +    "aliasNames": [
We should include the symbol and the `longName` to the list of known `aliases`.

2024-07-11 09:36 UTC, evertoncolling commented
I request a few changes, but overall looks good. When the changes are implemented, you can request a new review.

2024-07-11 09:37 UTC, evertoncolling requested changes
I requested a few changes, but overall looks good. When the changes are implemented, you can request a new review.

2024-07-12 14:11 UTC, spalla2-slb commented
Thanks @evertoncolling. I addressed your comments. Please re-review when you have a chance.

2024-07-15 07:24 UTC, evertoncolling commented on versions/v1/units.json
> +    "name": "Bel",
```suggestion
    "name": "B",
```
Here we'll have to change the name to `B`, to match the name in qudt. The `longName` can continue as is.

2024-07-17 10:29 UTC, evertoncolling approved these changes
Looks good to me

2024-07-17 10:30 UTC, merged