Update units.json | added units for gravity, spm and frequency
cognitedata/units-catalog pull request #97
Opened 2024-07-30 15:39 UTC by hanish2712

2024-08-08 19:21 UTC, evertoncolling commented on versions/v1/units.json
> +    "sourceReference": "https://qudt.org/vocab/unit/HZ"
You cannot link hecto hertz to the qudt reference for hertz. In this case, we can accept the following syntax:

```suggestion
    "source": "Custom based on qudt.org - https://qudt.org/vocab/unit/HZ",
    "sourceReference": null
```

2024-08-08 19:22 UTC, evertoncolling commented on versions/v1/units.json
> +    "sourceReference": "https://qudt.org/vocab/quantitykind/Gravity_API"
`sourceReference` expects a reference to a unit not a quantity.

```suggestion
    "sourceReference": "https://qudt.org/vocab/unit/DEGREE_API"
```

2024-08-08 19:23 UTC, evertoncolling commented on versions/v1/units.json
> +    "symbol": "API",
```suggestion
    "symbol": "°API",
```

2024-08-08 19:23 UTC, evertoncolling commented on versions/v1/units.json
> +    "longName": "API Gravity",
```suggestion
    "longName": "Degree API",
```

2024-08-08 19:23 UTC, evertoncolling commented on versions/v1/units.json
> +    "quantity": "Gravity_API",
```suggestion
    "quantity": "API Gravity",
```

2024-08-08 19:25 UTC, evertoncolling commented on versions/v1/units.json
> +    ],
```suggestion
      "deg API",
      "°API"
    ],
```

2024-08-08 19:32 UTC, evertoncolling commented on versions/v1/units.json
> +    "externalId": "gravity-api:api",
```suggestion
    "externalId": "api_gravity:degree_api",
```

2024-08-08 19:34 UTC, evertoncolling commented on versions/v1/units.json
> +    "name": "kAPI",
```suggestion
    "name": "k °API",
```

2024-08-08 19:35 UTC, evertoncolling commented on versions/v1/units.json
> +    "quantity": "Gravity_API",
```suggestion
    "quantity": "API Gravity",
```

2024-08-08 19:35 UTC, evertoncolling commented on versions/v1/units.json
> +    "externalId": "gravity-api:kilo-api",
```suggestion
    "externalId": "api_gravity:k__api",
```

2024-08-08 19:37 UTC, evertoncolling commented on versions/v1/units.json
> +    "longName": "Kilo API Gravity",
```suggestion
    "longName": "Kilo Degree API",
```

2024-08-08 19:37 UTC, evertoncolling commented on versions/v1/units.json
> +    ],
```suggestion
      "kgravity",
      "kgravit",
      "k °API"
    ],
```

2024-08-08 19:37 UTC, evertoncolling commented on versions/v1/units.json
> +    "symbol": "kAPI",
```suggestion
    "symbol": "k °API",
```

2024-08-08 19:38 UTC, evertoncolling commented on versions/v1/units.json
> +    "sourceReference": "https://qudt.org/vocab/quantitykind/Gravity_API"
```suggestion
    "source": "Custom based on qudt.org - https://qudt.org/vocab/unit/DEGREE_API",
    "sourceReference": null
```

2024-08-08 19:40 UTC, evertoncolling commented on versions/v1/units.json
> +    "name": "hecto-HZ",
```suggestion
    "name": "HectoHZ",
```

2024-08-08 19:41 UTC, evertoncolling commented on versions/v1/units.json
> +    "externalId": "frequency:hecto-hz",
```suggestion
    "externalId": "frequency:hectohz",
```

2024-08-08 19:50 UTC, evertoncolling commented on versions/v1/units.json
> +    "sourceReference": "https://petrowiki.spe.org/Sucker-rod_pumping_units"
This is not a valid reference. The page has no mention to strokes per minute, nor to conversion factors. Valid references are standards like [qudt.org](qudt.org), [Energistics](https://energistics.org/energistics-unit-of-measure-standard), [OPC-UA/UNECE](https://unece.org/trade/documents/2021/06/uncefact-rec20-0), or publications (see unit with `externalId = "energy:boe"`).

2024-08-08 19:55 UTC, evertoncolling requested changes
Thank you for your contribution to the Cognite Unit Catalog. Before we can approve this addition, a few changes are necessary:
- For SPM and HectoSPM: Please provide a trustworthy reference to verify these units.
- For the remaining units: I've left inline comments with specific suggestions. Please address these issues in your next update.

Once you've made these changes, feel free to request another review.

2024-08-12 19:39 UTC, evertoncolling commented
> Thanks @evertoncolling for your review. It has cleared many questions that I had. :)
> 
> I have changed a few things further.

Everything seems to be correct now with regards to the `units.json` file. Since you introduced a new quantity (API Gravity), we also need to modify the `unitSystems.json` file, specifying a default unit for the new quantity to at least the Default unit system. Once that is done, the PR tests should pass and we should be able to merge the new units.

2024-08-13 10:14 UTC, hanish2712 commented
Hello @evertoncolling  I've added the change in unitSystems.json as well.

1st test got passed but second one failed with an unknown error.

2024-08-13 12:57 UTC, polomani commented
@hanish2712 should be fixed now

2024-08-13 13:56 UTC, evertoncolling approved these changes
Everything looks good!

2024-08-13 13:56 UTC, merged